workflow secret testing

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,6 +22,14 @@ jobs:
         run: npm ci
         working-directory: ./backend
 
+      - name: Check AWS_ROLE_ARN is set
+        run: |
+          if [ -z "${{ secrets.AWS_ROLE_ARN }}" ]; then
+            echo "Secret AWS_ROLE_ARN is missing!" && exit 1
+          else
+            echo "Secret AWS_ROLE_ARN is set."
+          fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
